### ISSUE TITLE
Server-side rendering problem

### ISSUE THREAD

**Issue by adam-26** [Rezonans/redux-async-connect#12]
Hi, I'm having trouble rendering on the server. My app worked when I was using React-Router, but when trying to use this library my app no longer renders. The redux store is still serialized to the browser correctly, and the data looks as expected. However, no HTML is rendered.

I have debugged my code, and have found that on the server, everytime the `ReduxAsyncConnect.render()` method is called, `propsToShow` is always null:

``` javascript
render() {
    const {propsToShow} = this.state;
    return propsToShow && this.props.render(propsToShow);
  }
```

Here is my component:

``` javascript
class Homepage extends React.Component {

    static contextTypes = {
        store: React.PropTypes.object.isRequired
    };

    static reduxAsyncConnect(params, store) {
        const {dispatch, getState} = store;
        const promises = [];
        return Promise.all(promises);
    }

    render() {
        return (
            <div>
                <h2>Homepage</h2>
            </div>
        );
    }

}

export default Homepage;
```

No errors occur on the server. I know this isn't a lot to go on, but any assistance would be appreciated. I'm running out of ideas...

Thanks, Adam.

**Comment by sars** [comment]
Hi, @adam-26 
I fixed it in 0.1.8
check it please

**Comment by adam-26** [comment]
Hi @sars, it appears that in my case, `componentDidMount` is never called on the server...

Here is my render function (The props contain the correct values):

``` javascript
render() {
        return (
            <Provider store={ this.props.store }>
                <ReduxAsyncConnect {...this.props.renderProps} />
            </Provider>
        );
    }
```

**Comment by sars** [comment]
@adam-26, yes, my fault, sorry
i'm going to add tests shortly

0.1.9

check it please

**Comment by adam-26** [comment]
Thanks! That worked, and thanks for such a quick fix :)
Really like the component.

**Comment by sars** [comment]
@adam-26  You are welcome )
