### ISSUE TITLE
Incorrectly maps state to props

### ISSUE THREAD

**Issue by tadeuszwojcik** [Rezonans/redux-async-connect#13]
Cool library! I'm trying to integrate in my project, I've followed readme and added:
`
@asyncConnect({
  lunch: (params, store, helpers) => Promise.resolve({id: 1, name: 'Borsch'})
})
`
decorator, but in my components when I sue lunch it it doesn't return {id: 1, name: 'Bosh'} but object that has loading,loaded properties and data property that contains actual data. Is that how it's supposed to work, but perhaps not documented?

**Comment by sars** [comment]
@tadeuszwojcik , this is expected behaviour , need to update docs, yeah...
or change the behaviour. The thing is - you may want to react to loading prop somewhere else...
i don't know is it useful

**Comment by tadeuszwojcik** [comment]
I see, thanks for the clarification!
