### ISSUE TITLE
modifying state 

### ISSUE THREAD

**Issue by tadeuszwojcik** [Rezonans/redux-async-connect#14]
Hi,
I have scenario where I need to load some data from the server before rendering the view and that is well covered by that lib, but what about scenario that modifies such data (for example editing or load more that loads and add more items to the list), in such cases would you still recommend this lib?

**Comment by sars** [comment]
1. You can modify promise and return exactly what you want ... example:

``` js
client.get('/lunches').then(lunches => {extraKey: 'extraValue', lunches})
```

then will return new promise that will return modified data.
1. you can use only reduxAsyncConnect static method to delay rendering, like here:
   https://github.com/erikras/react-redux-universal-hot-example/commit/45673472165b25a0eecf1d2b45b7e793a16884c7#diff-0556f03522b596f0e507920a4e2fae60R38
   dispatch there actions you want, store data to state and connect them using regular redux-react connect
2. You can modify your data in render function.

Hope, this will help you

**Comment by tadeuszwojcik** [comment]
Cool, in my case I want to have fine grained control over data returned from the server I'll go with reduxAsyncConnect static method. 
Thanks for quick response :)
