### ISSUE TITLE
How to get the router query props

### ISSUE THREAD

**Issue by Vincz** [Rezonans/redux-async-connect#16]
Hi ! I'm trying to use redux async connect to pre-fetch data for a component server side.
I need not only the route params (provide by the "params" parameter of reduxAsyncConnect), but also the router query (containing a "page" parameter that i need to fetch the correct data). Any idea about how i could do that ? I tried to use redux-simple-router but in the fetch data, the correct location doesn't seem to be populated in the store.

**Comment by sars** [comment]
Hi @Vincz ,
sorry for late response.

Usually I use react-router-redux, so i have access to location from store:

helpers.store.getState().routing.location

But I think it make sense to add it directly to function params.
Now we have:

``` js
@asyncConnect({
  lunches: (params, helpers) => {
    // helpres.store, helpers.someOtherHelper
  }
})
```

In this case, I think it would be better to redesign this interface like:

``` js
@asyncConnect({
  lunches: ({store, params, location, helpers}) => {
    // ...
  }
})
```

What do you think?

**Comment by Keats** [comment]
How about having routing as a 2nd param that contains the params and the location ?

**Comment by sars** [comment]
@Keats , don you like such interface?

``` js
lunches: ({store, router, helpers})
```

**Comment by Keats** [comment]
Make sense to me, and you get the search etc from the router

**Comment by mmahalwy** [comment]
+1 to that

**Comment by sars** [comment]
hi guys, 
@evenchange4, take a look please:
https://github.com/Rezonans/redux-async-connect/tree/v1

there is new interface for @asyncConnect decorator in this version. 

Now you can use it like: 

``` js
@asyncConnect([
  {key: 'lunch', promise: ({params, helpers}) => helpers.client.get('/lunches/' + params.lunchId), group: 'smth'}
])
```

and then in your client.js:

``` js
const component = (
  <Router render={(props) =>
        <ReduxAsyncConnect {...props} filter={item => item.group === 'smth'} helpers={{client}} />
      } history={browserHistory}>
    {getRoutes(store, client)}
  </Router>
);
```

and server.js:

``` js
loadOnServer({...renderProps, store, helpers: {client}}).then(() => {
  // ...
}
```

now you have router in params as well

**Comment by Keats** [comment]
what's the reasoning behind having keys on decorator? If you are using that, you are using redux and you can just dispatch actions and connect to the store you're interested in with `connect` as usual

**Comment by sars** [comment]
@Keats , it's possible to use it without keys as well
If you are using then - async-connect will dispatch actions and connect result to your components automatically. If not - do it manually

**Comment by AVVS** [comment]
@sars current interface is extremely verbose, even though it gives extra flexibility. I would vouch to make it consistent with redux connect and make it look like this and also accept mapActionsToProps so that
there is really no need to call 2 decorators one after another, since it's already called internally

``` js
@asyncConnect(({ params, helpers, state }) => ({
  counter: state.counter, // sync prop, can as well be any random String, Number, etc
  lunch: () => Promise.resolve('borsch'), // function - wrapped with asyncConnect, resolved asynchronously
}))
```

**Comment by sars** [comment]
@AVVS this interface doesn't allow you create something like groups, like in example above. 
I thought several times about interface like you propose...

Also , i dons see how to implement such interface. I need to invoke the function to know what keys should be connected as sync, but i haven't state in that moment. So now i see only how to do only something like:

``` js
@asyncConnect(({ params, helpers, state }) => ({
  counter: () => state.counter, // sync prop, can as well be any random String, Number, etc
  lunch: () => Promise.resolve('borsch'), // function - wrapped with asyncConnect, resolved asynchronously
}))
```

Anyway.. it doesn't help to solve the issue with groups of props

**Comment by sars** [comment]
@AVVS, also, in interface above it's possible to avoid using key - in this case such data will not be connected. It's convenient when you want to dispatch own actions and store data manually

**Comment by sars** [comment]
it already works in 1.0.x version

**Comment by arkist** [comment]
@sars any docs? it seems still have no way to get query params.
it's not in the `params`, it in the `props.location`. so the way to access the `props` are needed.

**Comment by sars** [comment]
@arkist 
take a look please: 
https://github.com/sars/appetini-front/blob/appetini/src/containers/LunchDetails/LunchDetails.js#L19
