### ISSUE TITLE
Cannot use `connect` and `asyncConnect` on the same component

### ISSUE THREAD

**Issue by quicksnap** [Rezonans/redux-async-connect#17]
I'm reviewing the `simple-router` branch on RRUHE: https://github.com/erikras/react-redux-universal-hot-example/commit/45673472165b25a0eecf1d2b45b7e793a16884c7

Implementing it in my own project, everything works great! I like how I can define the static method `reduxAsyncConnect` and dispatch from there.

I was exploring using the decorator, but using that would prevent me from connecting to the rest of redux state.

Reading the code, is `store` available within 

We could resolve this a few ways. One way would be to change the API of `@asyncConnect` to accept params that pass through to `@connect`. Example: 

```
@asyncConnect(asyncMapStateToProps, [...normal connect params])
```

**Comment by sars** [comment]
Hi, @quicksnap 

actually, i don't see any problems with using both `@connect` and `@asyncConnect` decorators
https://github.com/sars/appetini-front/blob/appetini/src/containers/App/App.js#L20

What was the problem?...

**Comment by quicksnap** [comment]
I was coming across a rendering problem in my app.. perhaps it was something else.

Have you tested how this affects things when using `@connect` to bind to a non-redux-async-connect property? I wonder about `shouldComponentUpdate` of multiple `connect` calls clashing.

**Comment by quicksnap** [comment]
I'll try retesting in a bit. Reviewing [connect](https://github.com/rackt/react-redux/blob/master/src/components/connect.js#L79), it shouldn't cause any issues. Must have been on my end.

**Comment by sars** [comment]
@quicksnap , yeah... it should work fine ..
