### ISSUE TITLE
Decorator example incorrect

### ISSUE THREAD

**Issue by quicksnap** [Rezonans/redux-async-connect#18]
Following the example in the README doesn't yield correct props:

```
@asyncConnect({
  lunch: (params, helpers) => Promise.resolve({ id: 1, name: 'Borsch' })
})
```

![screenshot](https://dl.dropboxusercontent.com/spa/4moihw0kt47f2sy/dq5up65r.png)

The asyncConnect reducer has a nested key, `data`. So the example needs to be modified to `this.props.data.name`. Should reduxAsyncConnect reducer be modified to account for this nested key?

**Comment by sars** [comment]
@quicksnap , i need suggestion on this actually...
I added loading and loaded keys to be able to respond on loading process somewhere...
What do you think?

**Comment by quicksnap** [comment]
I'll give it some thought in a bit! There's a few approaches. Maybe it'd be helpful to have a `loadState` dictionary, such that `reduxAsyncConnect.loadState['lunch'].loading` contains what you'd expect, removing the need for `data`

**Comment by sars** [comment]
@quicksnap , yes, interesting idea...

**Comment by ahume** [comment]
Very new to thinking about this problem, but I think I prefer the resolved/loaded data to be directly on props because this matches the pattern of connect() in Redux.

**Comment by sars** [comment]
@quicksnap , @ahume - in 1.0.x version it works as @quicksnap proposed

**Comment by welljs** [comment]
Remove example with lunch , it doesn't works!
