### ISSUE TITLE
Error handling in loadOnServer

### ISSUE THREAD

**Issue by jhk2020** [Rezonans/redux-async-connect#21]
Hi, 
I was looking at the code for loadOnServer and was thinking that the error handling should come after '.then'. My code had a reference error and it took me a while to figure out why loadOnServer wasn't resolving. Any reason behind why it's before?

```
export function loadOnServer({ components, params }, store, helpers) {
  return Promise.all(asyncConnectPromises(filterAndFlattenComponents(components), params, store, helpers))
    .catch(error => console.error('reduxAsyncConnect server promise error: ' + error)).then(() => {
      store.dispatch(endGlobalLoad());
    });
}
```

**Comment by sars** [comment]
Hi @jhk2020 ,
catch goes before to modify promise, so the following "then" should be called always - whether original promise was failed or success

there is another branch actually that solves this problem another way:
https://github.com/Rezonans/redux-async-connect/blob/promise-errors/modules/ReduxAsyncConnect.js

**Comment by jhk2020** [comment]
Ah right, that makes sense. I'm getting a 'window is not defined' error after dispatching endGlobalLoad action, but that's a separate issue with my code. Thanks!
