### ISSUE TITLE
redux-thunk support?

### ISSUE THREAD

**Issue by babsonmatt** [Rezonans/redux-async-connect#25]
Right now my async actions use redux-thunk, so they return functions that return promises... is there anyway to handle this in redux-async-connect?

Right now I have to do something like:

``` js
@asyncConnect({
lunch: (params, { store: {dispatch, getState}}) => dispatch(getLunch)(dispatch, getState)
})

```

Thanks!

**Comment by sars** [comment]
@babsonmatt , why do you want to dispatch own actions here?..
asyncConnect dispatches them already - so you can react to them ...

**Comment by babsonmatt** [comment]
@sars, my mistake, I didn't realize that was the case.  Where does it get the actions to dispatch from?  Any chance there's a more real-world-ish example integrating with redux?

Edit: reduxAsyncConnect static method, I assume?

**Comment by babsonmatt** [comment]
@sars, I tried with the following, but same issues, the thunks dont get up getting processed correctly by middleware (no dispatch/getState being passed).  Any idea what may needed to make this work properly?

```js
  static reduxAsyncConnect(params, store, helpers) {
    const {dispatch, getState} = store;
    return dispatch(getForums)(dispatch, getState); // have to call the result of the dispatch with dispatch/getState
  }
```

**Comment by bhoomit** [comment]
@babsonmatt I have similar case. How did you solve this?

**Comment by babsonmatt** [comment]
@bhoomit I'm using this lib now: https://github.com/makeomatic/redux-connect

```
@asyncConnect([{
  promise: ({ params, store: { dispatch, getState } }) => {
    return dispatch(myAction(test));
  }
}])
```

**Comment by bhoomit** [comment]
@babsonmatt Cool, thanks :)
