### ISSUE TITLE
Option to not store result?

### ISSUE THREAD

**Issue by babsonmatt** [Rezonans/redux-async-connect#26]
Would it make sense to provide an option that would allow the result of the promise to not be stored by key?  For example, I'm just interested in being able to fire off a bunch of promises... their results will be handled by the reducers, so I don't need a duplicate copy of the data stored under reduxAsyncConnect.

Thank you!

**Comment by sars** [comment]
@babsonmatt you can implement it using reduxAsyncConnect static method :
https://github.com/Rezonans/redux-async-connect/blob/master/docs/API.MD#reduxasyncconnect-static-method

without decorator...

does it make sense?

**Comment by babsonmatt** [comment]
Makes sense, thanks!
