### ISSUE TITLE
Redirect if promise fails

### ISSUE THREAD

**Issue by jhk2020** [Rezonans/redux-async-connect#30]
Hi, 
I'm wondering what the best way is to redirect to a different component if a static reduxAsyncConnect method on a component falls. For example, if I'm trying to render a user-specific component and the user provides the wrong info, how do I redirect them back to the homepage when we are already committed to rendering the user page?

**Comment by sars** [comment]
hi @jhk2020 
Do you use react-router-redux?
you can use it to make such redirect in reduxAsyncConnect  method in particular

**Comment by jhk2020** [comment]
Would I do something like 'dispatch(routeActions.replace('/'))' within the reduxASyncConnect method?

**Comment by sars** [comment]
@jhk2020 Yes, you can use this way so far. I'm planning to include router in argument in closest future. But so far you can use dispatch

**Comment by wmarsey** [comment]
@jhk2020 Did you get this working? I have the below and the location doesn't change, unsure why. @sars is this how you see it working?

```
RestrictedPage.js

import { replace } from 'react-router-redux';

@asyncConnect([{
  promise: ({store: {dispatch, getState}}) => {
    const promises = [];

    // promises created here 

    return Promise.all(promises).then(() => {
        const user = getState().auth.user;
        if(isEmpty(user)) return dispatch(replace('/login'));
    });
  }
}])
```

It manages to get to the `replace()` function call, but the location doesn't change...

**Comment by dawidvdh** [comment]
Hey Guys in the exact same boat, I am doing this currently:

``` javascript
@asyncConnect([{
  promise: ({ store: { dispatch, getState }, params: { category, page = 1 }, router }) => {
    const promises = [];

    if (!isLoaded(getState(), category, page)) {
      promises.push(dispatch(load(category, page)));
    }

    return Promise.all(promises).then(() => {
      dispatch(loadFromFeatured(slides, activeSlide));
    }).catch(() => {
      dispatch(router.replace('/404'));
    });
  }
}])
```

but unfortunately it only redirects on the client and not on the server side... so basically if i hit this url correctly it doesn't replace when there is a error, can log other things out of the catch but replace never happens server side.

Any Help would be Greatly Appreciated.

**Comment by dshiells** [comment]
+1 Anyone find a solution to the above?

**Comment by faiz-voonik** [comment]
I'm also facing the same issue. Please help.

**Comment by bertho-zero** [comment]
I'm also facing to the same issue.
