### ISSUE TITLE
Integrating with Immutable.js

### ISSUE THREAD

**Issue by hung-phan** [Rezonans/redux-async-connect#35]
Hi,

Thanks for this library. I just wonder if this library can be integrated with `Immutable.js`. The problem is the current integration of `isLoaded` function depended on `this.context.store.getState().reduxAsyncConnect.loaded;`. If we can have a selector function, this would be nice

**Comment by sars** [comment]
@hung-phan there is no integration with Immutable.js, but i would love to add it...
I'll comment your PR

**Comment by MaxSvargal** [comment]
+1, i have this problem too
