### ISSUE TITLE
Possible to run reduxAsyncConnect in order?

### ISSUE THREAD

**Issue by x1a0** [Rezonans/redux-async-connect#37]
Thanks for this project.

In my project I always load user's data on all pages - so in the very root component (<App>) there is a `reduxAsyncConnect` method which does that.
Then in all children component they also fetch data they need - but assume user's data is loaded.

However this project seems to flatten all `reduxAsyncConnect` and run them simultaneously.

Would it be better if it keeps the depending tree based on component tree?

**Comment by sars** [comment]
Hi @x1a0,
In my project i solved this problem like this:
https://github.com/sars/appetini-front/blob/appetini/src/routes.js#L23

Right now there is no possibility to invoke reduxAcyncConnect in sequence ...

**Comment by x1a0** [comment]
@sars Thanks - This is helpful. Maybe this is the right way to solve such problem as `user` is sort of a special data.
