### ISSUE TITLE
postinstall step not babel 6 friendly

### ISSUE THREAD

**Issue by bdefore** [Rezonans/redux-async-connect#4]
If redux-async-connect is included in a project that uses Babel 6, and they don't specify a `.babelrc` in their project that doesn't use `stage-0` preset, they'll get the following postinstall error:

```
> redux-async-connect@0.1.3 build /Users/d4/code/universal-redux-starter/node_modules/redux-async-connect
> babel ./modules --stage 0 --loose all -d lib --ignore '__tests__'

SyntaxError: modules/ReduxAsyncConnect.js: Unexpected token (51:19)
  49 |
  50 | class ReduxAsyncConnect extends React.Component {
> 51 |   static propTypes = {
     |                    ^
  52 |     components: array.isRequired,
  53 |     params: object.isRequired,
  54 |     location: object.isRequired,
```

I suggest either updating to use `babel-cli` at `~6.4` or use a `prepublish` step rather than a `postinstall`.

**Comment by sars** [comment]
@bdefore , yes, i'd like to update to babel 6...

**Comment by sars** [comment]
@bdefore , it should work correctly now...
