### ISSUE TITLE
is it possible to not delay page transition? (client)

### ISSUE THREAD

**Issue by babsonmatt** [Rezonans/redux-async-connect#42]
If not would such an option be useful?  I don't always want to hold up the page transition so having this as an option would be nice

**Comment by sars** [comment]
@babsonmatt take a look please:
https://github.com/erikras/react-redux-universal-hot-example/pull/928/files

**Comment by babsonmatt** [comment]
@sars I took a look but unfortunately I'm not sure I follow, what should I be taking away from this example? Thanks.

**Comment by babsonmatt** [comment]
Nevermind... got it! Didn't know filter was a thing... thanks!

**Comment by sars** [comment]
@babsonmatt your are welcome.
I need to add docs....
