### ISSUE TITLE
Support react-v15.0.1

### ISSUE THREAD

**Issue by igoldny** [Rezonans/redux-async-connect#75]
http://facebook.github.io/react/blog/2016/04/08/react-v15.0.1.html

**Comment by peleteiro** [comment]
Any news?

I'm using a fork only changing react version on package.json and it seems to work.

**Comment by berdof** [comment]
Does anyone knows alternatives for this library  with 15.0.1 react support?

**Comment by andreijs** [comment]
Nothing broke for me on react 15.0.1 use npm 3 maybe it doesn't have peer dependency ?

**Comment by igoldny** [comment]
i get this error:

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-addons-test-utils@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer redbox-react@1.2.3 wants react@>=0.13.2 || ^0.14.0-rc1 || ^15.0.0-rc
npm ERR! peerinvalid Peer redux-async-connect@1.0.0-rc4 wants react@0.14.x
npm ERR! peerinvalid Peer redux-devtools@3.2.0 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer redux-devtools-dock-monitor@1.1.1 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer redux-devtools-log-monitor@1.0.11 wants react@^0.14.0 || ^15.0.0-0

**Comment by AVVS** [comment]
use npm@3

Also you can use `npm i AVVS/redux-async-connect#v2.0.0` to have slightly reworked version (nested promises are loaded in series instead of in parallel) and proper transforms are added

If there is interest I might be able to start maintaining this, but we need to see that first

**Comment by igoldny** [comment]
with npm@3:
npm WARN redux-async-connect@1.0.0-rc4 requires a peer of react@0.14.x but none was installed.

**Comment by AVVS** [comment]
Thats just a warn, it doesnt matter

**Comment by igoldny** [comment]
Most of the major providers do not support by default npm@3 for now (maybe because its still super slow)

**Comment by AVVS** [comment]
`npm i -g npm@3`

**Comment by igoldny** [comment]
duh!
i'm using amazon elastic beanstalk, i can't change it to npm@3...

**Comment by AVVS** [comment]
check https://github.com/makeomatic/redux-connect - can help

**Comment by alangumer** [comment]
Here the updated npm dependencies working with react-v15.0.1 and redux-connect that @AVVS had suggested (in components and containers replace the references to redux-async-connect by redux-connect)

"dependencies": {
    "babel-core": "^6.5.2",
    "babel-loader": "^6.2.1",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-react-display-name": "^6.3.13",
    "babel-plugin-transform-runtime": "^6.3.13",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.3.13",
    "babel-runtime": "^6.3.19",
    "body-parser": "^1.14.1",
    "compression": "^1.6.0",
    "express": "^4.13.3",
    "express-session": "^1.12.1",
    "file-loader": "^0.8.5",
    "hoist-non-react-statics": "^1.0.3",
    "http-proxy": "^1.12.0",
    "invariant": "^2.2.0",
    "less": "^2.5.3",
    "less-loader": "^2.2.1",
    "lru-memoize": "^1.0.0",
    "map-props": "^1.0.0",
    "material-ui": "^0.15.0",
    "multireducer": "^2.0.0",
    "piping": "^0.3.0",
    "pretty-error": "^1.2.0",
    "react": "^15.0.0",
    "react-dom": "^15.0.0",
    "react-helmet": "^2.2.0",
    "react-inline-css": "^2.0.0",
    "react-redux": "^4.0.0",
    "react-router": "2.0.0",
    "react-router-redux": "^4.0.0",
    "redux": "^3.0.4",
    "redux-connect": "^2.4.0",
    "redux-form": "^3.0.12",
    "scroll-behavior": "^0.3.2",
    "serialize-javascript": "^1.1.2",
    "serve-favicon": "^2.3.0",
    "socket.io": "^1.3.7",
    "socket.io-client": "^1.3.7",
    "superagent": "^1.4.0",
    "url-loader": "^0.5.7",
    "warning": "^2.1.0",
    "webpack-isomorphic-tools": "^2.2.18"
  },
  "devDependencies": {
    "autoprefixer-loader": "^3.1.0",
    "babel-eslint": "^5.0.0-beta6",
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-typecheck": "^3.6.0",
    "better-npm-run": "0.0.8",
    "bootstrap-sass": "^3.3.5",
    "bootstrap-sass-loader": "^1.0.9",
    "chai": "^3.3.0",
    "clean-webpack-plugin": "^0.1.6",
    "concurrently": "^0.1.1",
    "css-loader": "^0.23.1",
    "eslint": "1.10.3",
    "eslint-config-airbnb": "0.1.0",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-import": "^0.8.0",
    "eslint-plugin-react": "^3.5.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "font-awesome": "^4.4.0",
    "font-awesome-webpack": "0.0.4",
    "json-loader": "^0.5.4",
    "karma": "^0.13.10",
    "karma-cli": "^0.1.1",
    "karma-mocha": "^0.2.0",
    "karma-mocha-reporter": "^1.1.1",
    "karma-phantomjs-launcher": "^0.2.1",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.7.0",
    "mocha": "^2.3.3",
    "node-sass": "^3.4.2",
    "phantomjs": "^1.9.18",
    "phantomjs-polyfill": "0.0.1",
    "react-a11y": "^0.2.6",
    "react-addons-test-utils": "^15.0.0",
    "react-transform-catch-errors": "^1.0.0",
    "react-transform-hmr": "^1.0.1",
    "redbox-react": "^1.1.1",
    "redux-devtools": "^3.0.0-beta-3",
    "redux-devtools-dock-monitor": "^1.0.0-beta-3",
    "redux-devtools-log-monitor": "^1.0.0-beta-3",
    "sass-loader": "^3.1.2",
    "sinon": "^1.17.2",
    "strip-loader": "^0.1.0",
    "style-loader": "^0.13.0",
    "timekeeper": "0.0.5",
    "webpack": "^1.12.9",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.5.0"
  },

**Comment by AVVS** [comment]
**_warn**_ [redux-connect](https://github.com/makeomatic/redux-connect) changed syntax a bit, so you'll have to do migration (basically 2-3 lines of code)
